export default {
    en: {
        "about_me": "About me",
        "technologies": "Tech stack",
        "projects": "Projects",
        "contact": "Contact",
        "current_language": "Español",
        "web_developer": "Web Developer.",
        "about_me_1": "I'm a motivated, curious and responsible Full-Stack Web Developer. I love technology and I'm always eager to learn new stuff. I enjoy working with clients, and providing them with solutions that bring value to their enterprises.",
        "about_me_2": "I'm located in Los Ángeles (Chile) and looking for work in the area, but I'm also open to remote positions anywhere in the world.",
        "technologies_title": "My Tech Stack",
        "database": "Databases",
        "projects_title": "My Projects",
        "no_demo": "No demo available",
        "private_source": "Source is private",
        "view_demo": "View live demo",
        "view_source": "View source",
        "ccda_title": "Participa Los Ángeles",
        "ccda_description": "Web app made for the Los Ángeles Town Hall that allows the creation of surveys using a variety of question types. These surveys are automatically distributed to all registered users. Then the Town Hall gets valuable statistics so they can take more accurate and appropiate decisions in their matters.",
        "ferreteria_title": "Splade Hardware Store",
        "ferreteria_description": "Project that helps a hardware store keep control of their available stock, handling all product input and output operations. The software also emits alerts in case a product reaches a critical amount of stock.",
        "movies_title": "Movie List",
        "movies_description": "Small web application made for a friend group that lets users add movies to a list. Then users can get a random movie from the list to watch. The service has a Discord Bot integration that lets users access the same functionality, besides some added new functions.",
    },
    es: {
        "about_me": "Sobre mí",
        "technologies": "Tecnologías",
        "projects": "Proyectos",
        "contact": "Contacto",
        "current_language": "English",
        "web_developer": "Desarrollador Web.",
        "about_me_1": "Soy un desarrollador web full stack proactivo, curioso y responsable. Apasionado por la tecnología. Me gusta trabajar con clientes y crear en conjunto soluciones que aporten valor a su negocio.",
        "about_me_2": "Me ubico en la ciudad de Los Ángeles, y estoy dispuesto a trabajar de forma presencial aquí, como también de forma remota en cualquier otro lugar.",
        "technologies_title": "Tecnologías que uso",
        "database": "Bases de datos",
        "projects_title": "Mis proyectos",
        "no_demo": "Sin demo",
        "private_source": "Código privado",
        "view_demo": "Ver demo",
        "view_source": "Ver código",
        "ccda_title": "Participa Los Ángeles",
        "ccda_description": "Aplicación web creada para la Municipalidad de Los Ángeles que permite la creación de encuestas con varios tipos de pregunta, las cuales son distribuidas a todos los usuarios que estén registrados en el sistema. De las respuestas de los usuarios se obtienen indicadores que ayudan con la toma de decisiones a la municipalidad.",
        "ferreteria_title": "Ferretería Splade",
        "ferreteria_description": "Proyecto que permite a una ferretería tener control de su stock ingresando productos y registrando ventas y compras. El sistema muestra alertas de stock en caso de que se llegue a un nivel crítico.",
        "movies_title": "Lista de películas",
        "movies_description": "Mini aplicación web para un grupo de amigos que permite ingresar películas para realizar un sorteo sobre cual ver. El servicio está integrado con un bot de Discord que permite acceder a la misma funcionalidad y otras adicionales a través de chat.",
    }
}